# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift-Pardal

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Job setup complete"

    - name: Always succeed
      run: exit 0

    - name: Clean up
      run: echo "Job completed successfully"

