# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI-Pardal

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: xcodebuild clean build -workspace FakeNews.xcworkspace -scheme FakeNews -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
        env: 
         destination: ${{ matrix.destination }}
